language: python
python:
  - 2.7
    #  - 3.4
  - 3.6
    #  - pypy
    #  - pypy3
    #matrix:
    #  allow_failures:
    #    - python: 3.4
    #    - python: pypy
    #    - python: pypy3

before_install:
  - sudo apt-get update -qq

  # dependency for pygpgme (see requirements.txt)
  - sudo apt-get install -qq libgpgme11-dev

  # pylint for checking coding style
  #- sudo apt-get install -qq pylint

install:
  - pip install -r requirements.txt

script:
  # run pytest while making zeyple as python module available
  # (see tests folder)
  - PYTHONPATH=. pytest

after_script:
  # run coding style tests
  # (will not fail buld)
  - pylint zeyple -f colorized -r no
